name: homerent_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/home.png
    - images/Layer 2.png
    - images/logo2.png
    - images/logo3.png
    - images/hut2.png
    - images/hut1.png
    - images/Ellipse 4.png
    - images/purple.png
    - images/Vector.png
