// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDNetc2zDReFXiD-V6oIr7i7L135E48rM',
    appId: '1:545430179280:web:bc877a11cce2cbe10b7dd5',
    messagingSenderId: '545430179280',
    projectId: 'todo-demo-b51da',
    authDomain: 'todo-demo-b51da.firebaseapp.com',
    storageBucket: 'todo-demo-b51da.appspot.com',
    measurementId: 'G-J7D7E4FDFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeus5mMx3RNQeURqZIytHLThg-FoU3_bg',
    appId: '1:545430179280:android:97c1eed0a6aabddf0b7dd5',
    messagingSenderId: '545430179280',
    projectId: 'todo-demo-b51da',
    storageBucket: 'todo-demo-b51da.appspot.com',
  );
}
